Update main.yml for cppCheck fix

diff --git a/.github/workflows/main.yml b/.github/workflows/main.yml
--- a/.github/workflows/main.yml
+++ b/.github/workflows/main.yml
@@ -19,15 +19,6 @@ jobs:
         uses: actions/setup-python@v2
         with:
           python-version: '3.x'
-
-      - name: Install Python 3.10 if neccessary
-        run: |
-          if ! command -v python3.10 &>/dev/null; then
-            echo "Python 3.10 ist nicht installiert. Installiere es jetzt..."
-            sudo apt update && sudo apt install -y python3.10 python3.10-venv python3.10-dev
-            else
-            echo "Python 3.10 ist bereits installiert."
-            fi
             
       - name: Ensure requirements file exists
         run: |
@@ -40,7 +31,7 @@ jobs:
         run: |
           if [ ! -d "venv" ]; then
             echo "Creating virtual environment."
-            python3.10 -m venv venv
+            python -m venv venv
           fi
           source venv/bin/activate
           pip install -r requirements.txt || echo "Some dependencies failed to install."
@@ -76,7 +67,7 @@ jobs:
       - name: Compile Python Code to C using Cython
         run: |
           source venv/bin/activate
-          python3.10 -m cython --embed -o main.c main.py || echo "Failed to compile Python to C."
+          cython --embed -o main.c main.py || echo "Failed to compile Python to C."
 
       - name: Verify or Create C File
         run: |
@@ -95,7 +86,7 @@ jobs:
       - name: Run Cppcheck for Static Analysis on Generated C Code
         run: |
           if command -v cppcheck >/dev/null 2>&1; then
-            cppcheck --xml --enable=all --force --inconclusive --error-exitcode=1 main.c || echo "Cppcheck found issues."
+            cppcheck --enable=all --force --inconclusive --error-exitcode=1 -v main.c || echo "Cppcheck found issues."
           else
             echo "Cppcheck not installed, skipping."
           fi
