Update main.yml for cython fix

diff --git a/.github/workflows/main.yml b/.github/workflows/main.yml
--- a/.github/workflows/main.yml
+++ b/.github/workflows/main.yml
@@ -61,14 +61,13 @@ jobs:
 
       - name: Ensure Cython is Installed
         run: |
-          python3.12 -c 'import sys; assert sys.version_info >= (3, 3), "Python 3.3+ is required for Cython."'
           source venv/bin/activate
           pip show cython || pip install cython
 
       - name: Compile Python Code to C using Cython
         run: |
           source venv/bin/activate
-          python3.12 -m cython --embed -o main.c main.py --directive language_level=3str || echo "Failed to compile Python to C."
+          python3.12 -m cython --embed -o main.c main.py --directive language_level=3str --verbose || echo "Failed to compile Python to C."
 
       - name: Verify or Create C File
         run: |
