Update main.yml to cppCheck

diff --git a/.github/workflows/main.yml b/.github/workflows/main.yml
--- a/.github/workflows/main.yml
+++ b/.github/workflows/main.yml
@@ -76,16 +76,19 @@ jobs:
             touch main.c
           fi          
 
-      - name: Install Clang if Not Available
+      - name: Install Cppcheck if Not Available
         run: |
-          if ! command -v clang >/dev/null 2>&1; then
-            echo "Clang not found. Installing..."
-            sudo apt-get update -y && sudo apt-get install -y clang
+          if ! command -v cppcheck >/dev/null 2>&1; then
+            echo "Cppcheck not found. Installing..."
+            sudo apt-get update -y && sudo apt-get install -y cppcheck
           fi
-
-      - name: Run Clang Static Analyzer for Static Analysis on Generated C Code
+      - name: Run Cppcheck for Static Analysis on Generated C Code
         run: |
-          clang --analyze main.c || echo "Clang Static Analyzer found issues."
+          if command -v cppcheck >/dev/null 2>&1; then
+            cppcheck --enable=all --inconclusive --error-exitcode=1 -v main.c || echo "Cppcheck found issues."
+          else
+            echo "Cppcheck not installed, skipping."
+          fi
 
       - name: Run Flawfinder for Security Analysis on Generated C Code
         run: |
