Update main.yml

diff --git a/.github/workflows/main.yml b/.github/workflows/main.yml
--- a/.github/workflows/main.yml
+++ b/.github/workflows/main.yml
@@ -20,11 +20,6 @@ jobs:
         with:
           python-version: '3.x'
 
-      - name: Install Python Development Packages
-        run: |
-          sudo apt-get update
-          sudo apt-get install -y python3-dev python3.12-dev
-
       - name: Ensure requirements file exists
         run: |
           if [ ! -f "requirements.txt" ]; then
@@ -72,7 +67,7 @@ jobs:
       - name: Compile Python Code to C using Cython
         run: |
           source venv/bin/activate
-          python3.12 -m cython --embed -o main.c main.py --directive language_level=3 || echo "Failed to compile Python to C."
+          python3.12 -m cython --embed -o main.c main.py --directive language_level=3str || echo "Failed to compile Python to C."
 
       - name: Verify or Create C File
         run: |
